export interface IPlex {
	"ratingKey"?: string,
	"key"?: string,
	"guid"?: string,
	"studio"?: string,
	"type"?: string,
	"title"?: string,
	"originalTitle"?: string,
	"titleSort"?: string,
	"contentRating"?: string,
	"summary"?: string,
	"rating"?: number,
	"audienceRating"?: number,
	"viewCount"?: number,
	"viewOffset"?: number,
	"skipCount"?: number,
	"lastViewedAt"?: number,
	"year"?: number,
	"tagline"?: string,
	"thumb"?: string,
	"art"?: string,
	"duration"?: number,
	"originallyAvailableAt"?: string,
	"addedAt"?: number,
	"updatedAt"?: number,
	"audienceRatingImage"?: string,
	"chapterSource"?: string,
	"hasPremiumExtras"?: string,
	"hasPremiumPrimaryExtra"?: string,
	"ratingImage"?: string,
	"Media"?: IMedia[],
	"Genre"?: { "tag": string }[],
	"Director"?: { "tag": string }[],
	"Writer"?: { "tag": string }[],
	"Country"?: { "tag": string }[],
	"Role"?: { "tag": string }[],
	"userRating"?: number,
	"lastRatedAt"?: number,
}

export interface IMedia {
	"id": number,
	"duration"?: number,
	"bitrate"?: number,
	"width"?: number,
	"height"?: number,
	"aspectRatio"?: number,
	"audioChannels"?: number,
	"audioCodec"?: string,
	"videoCodec"?: string,
	"videoResolution"?: string,
	"container"?: string,
	"videoFrameRate"?: string,
	"audioProfile"?: string,
	"videoProfile"?: string,
	"optimizedForStreaming"?: number,
	"has64bitOffsets"?: boolean,
	"Part": IPart[],
}

export interface IPart {
	"id": number,
	"key"?: string,
	"duration"?: number,
	"file"?: string,
	"size"?: number,
	"container"?: string,
	"packetLength"?: number,
	"audioProfile"?: string,
	"hasThumbnail"?: string,
	"has64bitOffsets"?: boolean,
	"hasChapterVideoStream"?: boolean,
	"timeStamp"?: boolean,
	"videoProfile"?: string
	"optimizedForStreaming"?: boolean,
}
